require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GranularidadeGeograficasController do

  # This should return the minimal set of attributes required to create a valid
  # GranularidadeGeografica. As you add validations to GranularidadeGeografica, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GranularidadeGeograficasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all granularidade_geograficas as @granularidade_geograficas" do
      granularidade_geografica = GranularidadeGeografica.create! valid_attributes
      get :index, {}, valid_session
      assigns(:granularidade_geograficas).should eq([granularidade_geografica])
    end
  end

  describe "GET show" do
    it "assigns the requested granularidade_geografica as @granularidade_geografica" do
      granularidade_geografica = GranularidadeGeografica.create! valid_attributes
      get :show, {:id => granularidade_geografica.to_param}, valid_session
      assigns(:granularidade_geografica).should eq(granularidade_geografica)
    end
  end

  describe "GET new" do
    it "assigns a new granularidade_geografica as @granularidade_geografica" do
      get :new, {}, valid_session
      assigns(:granularidade_geografica).should be_a_new(GranularidadeGeografica)
    end
  end

  describe "GET edit" do
    it "assigns the requested granularidade_geografica as @granularidade_geografica" do
      granularidade_geografica = GranularidadeGeografica.create! valid_attributes
      get :edit, {:id => granularidade_geografica.to_param}, valid_session
      assigns(:granularidade_geografica).should eq(granularidade_geografica)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GranularidadeGeografica" do
        expect {
          post :create, {:granularidade_geografica => valid_attributes}, valid_session
        }.to change(GranularidadeGeografica, :count).by(1)
      end

      it "assigns a newly created granularidade_geografica as @granularidade_geografica" do
        post :create, {:granularidade_geografica => valid_attributes}, valid_session
        assigns(:granularidade_geografica).should be_a(GranularidadeGeografica)
        assigns(:granularidade_geografica).should be_persisted
      end

      it "redirects to the created granularidade_geografica" do
        post :create, {:granularidade_geografica => valid_attributes}, valid_session
        response.should redirect_to(GranularidadeGeografica.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved granularidade_geografica as @granularidade_geografica" do
        # Trigger the behavior that occurs when invalid params are submitted
        GranularidadeGeografica.any_instance.stub(:save).and_return(false)
        post :create, {:granularidade_geografica => {}}, valid_session
        assigns(:granularidade_geografica).should be_a_new(GranularidadeGeografica)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GranularidadeGeografica.any_instance.stub(:save).and_return(false)
        post :create, {:granularidade_geografica => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested granularidade_geografica" do
        granularidade_geografica = GranularidadeGeografica.create! valid_attributes
        # Assuming there are no other granularidade_geograficas in the database, this
        # specifies that the GranularidadeGeografica created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GranularidadeGeografica.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => granularidade_geografica.to_param, :granularidade_geografica => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested granularidade_geografica as @granularidade_geografica" do
        granularidade_geografica = GranularidadeGeografica.create! valid_attributes
        put :update, {:id => granularidade_geografica.to_param, :granularidade_geografica => valid_attributes}, valid_session
        assigns(:granularidade_geografica).should eq(granularidade_geografica)
      end

      it "redirects to the granularidade_geografica" do
        granularidade_geografica = GranularidadeGeografica.create! valid_attributes
        put :update, {:id => granularidade_geografica.to_param, :granularidade_geografica => valid_attributes}, valid_session
        response.should redirect_to(granularidade_geografica)
      end
    end

    describe "with invalid params" do
      it "assigns the granularidade_geografica as @granularidade_geografica" do
        granularidade_geografica = GranularidadeGeografica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GranularidadeGeografica.any_instance.stub(:save).and_return(false)
        put :update, {:id => granularidade_geografica.to_param, :granularidade_geografica => {}}, valid_session
        assigns(:granularidade_geografica).should eq(granularidade_geografica)
      end

      it "re-renders the 'edit' template" do
        granularidade_geografica = GranularidadeGeografica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GranularidadeGeografica.any_instance.stub(:save).and_return(false)
        put :update, {:id => granularidade_geografica.to_param, :granularidade_geografica => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested granularidade_geografica" do
      granularidade_geografica = GranularidadeGeografica.create! valid_attributes
      expect {
        delete :destroy, {:id => granularidade_geografica.to_param}, valid_session
      }.to change(GranularidadeGeografica, :count).by(-1)
    end

    it "redirects to the granularidade_geograficas list" do
      granularidade_geografica = GranularidadeGeografica.create! valid_attributes
      delete :destroy, {:id => granularidade_geografica.to_param}, valid_session
      response.should redirect_to(granularidade_geograficas_url)
    end
  end

end
