#encoding: UTF-8

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrgaosController do

  # This should return the minimal set of attributes required to create a valid
  # Orgao. As you add validations to Orgao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrgaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all orgaos as @orgaos" do
      orgao = Orgao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orgaos).should eq([orgao])
    end
  end

  describe "GET show" do
    it "assigns the requested orgao as @orgao" do
      orgao = Orgao.create! valid_attributes
      get :show, {:id => orgao.to_param}, valid_session
      assigns(:orgao).should eq(orgao)
    end
  end

  describe "GET new" do
    it "assigns a new orgao as @orgao" do
      get :new, {}, valid_session
      assigns(:orgao).should be_a_new(Orgao)
    end
  end

  describe "GET edit" do
    it "assigns the requested orgao as @orgao" do
      orgao = Orgao.create! valid_attributes
      get :edit, {:id => orgao.to_param}, valid_session
      assigns(:orgao).should eq(orgao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orgao" do
        expect {
          post :create, {:orgao => valid_attributes}, valid_session
        }.to change(Orgao, :count).by(1)
      end

      it "assigns a newly created orgao as @orgao" do
        post :create, {:orgao => valid_attributes}, valid_session
        assigns(:orgao).should be_a(Orgao)
        assigns(:orgao).should be_persisted
      end

      it "redirects to the created orgao" do
        post :create, {:orgao => valid_attributes}, valid_session
        response.should redirect_to(Orgao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orgao as @orgao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orgao.any_instance.stub(:save).and_return(false)
        post :create, {:orgao => {}}, valid_session
        assigns(:orgao).should be_a_new(Orgao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orgao.any_instance.stub(:save).and_return(false)
        post :create, {:orgao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orgao" do
        orgao = Orgao.create! valid_attributes
        # Assuming there are no other orgaos in the database, this
        # specifies that the Orgao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Orgao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => orgao.to_param, :orgao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested orgao as @orgao" do
        orgao = Orgao.create! valid_attributes
        put :update, {:id => orgao.to_param, :orgao => valid_attributes}, valid_session
        assigns(:orgao).should eq(orgao)
      end

      it "redirects to the orgao" do
        orgao = Orgao.create! valid_attributes
        put :update, {:id => orgao.to_param, :orgao => valid_attributes}, valid_session
        response.should redirect_to(orgao)
      end
    end

    describe "with invalid params" do
      it "assigns the orgao as @orgao" do
        orgao = Orgao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orgao.any_instance.stub(:save).and_return(false)
        put :update, {:id => orgao.to_param, :orgao => {}}, valid_session
        assigns(:orgao).should eq(orgao)
      end

      it "re-renders the 'edit' template" do
        orgao = Orgao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orgao.any_instance.stub(:save).and_return(false)
        put :update, {:id => orgao.to_param, :orgao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orgao" do
      orgao = Orgao.create! valid_attributes
      expect {
        delete :destroy, {:id => orgao.to_param}, valid_session
      }.to change(Orgao, :count).by(-1)
    end

    it "redirects to the orgaos list" do
      orgao = Orgao.create! valid_attributes
      delete :destroy, {:id => orgao.to_param}, valid_session
      response.should redirect_to(orgaos_url)
    end
  end

  describe "GET search" do
	
		it 'should render search template' do
			get :search, {:q => 'ministério'}, valid_session
			response.should render_template 'search'
		end
	end
end
