require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoLinksController do

  # This should return the minimal set of attributes required to create a valid
  # TipoLink. As you add validations to TipoLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipoLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipo_links as @tipo_links" do
      tipo_link = TipoLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipo_links).should eq([tipo_link])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_link as @tipo_link" do
      tipo_link = TipoLink.create! valid_attributes
      get :show, {:id => tipo_link.to_param}, valid_session
      assigns(:tipo_link).should eq(tipo_link)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_link as @tipo_link" do
      get :new, {}, valid_session
      assigns(:tipo_link).should be_a_new(TipoLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_link as @tipo_link" do
      tipo_link = TipoLink.create! valid_attributes
      get :edit, {:id => tipo_link.to_param}, valid_session
      assigns(:tipo_link).should eq(tipo_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoLink" do
        expect {
          post :create, {:tipo_link => valid_attributes}, valid_session
        }.to change(TipoLink, :count).by(1)
      end

      it "assigns a newly created tipo_link as @tipo_link" do
        post :create, {:tipo_link => valid_attributes}, valid_session
        assigns(:tipo_link).should be_a(TipoLink)
        assigns(:tipo_link).should be_persisted
      end

      it "redirects to the created tipo_link" do
        post :create, {:tipo_link => valid_attributes}, valid_session
        response.should redirect_to(TipoLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_link as @tipo_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoLink.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_link => {}}, valid_session
        assigns(:tipo_link).should be_a_new(TipoLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoLink.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_link => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipo_link" do
        tipo_link = TipoLink.create! valid_attributes
        # Assuming there are no other tipo_links in the database, this
        # specifies that the TipoLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TipoLink.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tipo_link.to_param, :tipo_link => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tipo_link as @tipo_link" do
        tipo_link = TipoLink.create! valid_attributes
        put :update, {:id => tipo_link.to_param, :tipo_link => valid_attributes}, valid_session
        assigns(:tipo_link).should eq(tipo_link)
      end

      it "redirects to the tipo_link" do
        tipo_link = TipoLink.create! valid_attributes
        put :update, {:id => tipo_link.to_param, :tipo_link => valid_attributes}, valid_session
        response.should redirect_to(tipo_link)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_link as @tipo_link" do
        tipo_link = TipoLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_link.to_param, :tipo_link => {}}, valid_session
        assigns(:tipo_link).should eq(tipo_link)
      end

      it "re-renders the 'edit' template" do
        tipo_link = TipoLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_link.to_param, :tipo_link => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_link" do
      tipo_link = TipoLink.create! valid_attributes
      expect {
        delete :destroy, {:id => tipo_link.to_param}, valid_session
      }.to change(TipoLink, :count).by(-1)
    end

    it "redirects to the tipo_links list" do
      tipo_link = TipoLink.create! valid_attributes
      delete :destroy, {:id => tipo_link.to_param}, valid_session
      response.should redirect_to(tipo_links_url)
    end
  end

end
